language: cpp
compiler:
  - gcc
os:
  - linux
  - osx
before_install:
  - test "$TRAVIS_OS_NAME" != linux || sudo apt-get -qq update
  - test "$TRAVIS_OS_NAME" != linux || sudo apt-get -qq install libwxgtk3.0-dev libavcodec-dev libavformat-dev libproj-dev libswscale-dev mesa-common-dev libglu1-mesa-dev libx11-dev libxext-dev x11proto-core-dev liblocale-po-perl unifont sgmltools-lite jadetex docbook-to-man w3m
  - test "$TRAVIS_OS_NAME" != osx || brew update
  - test "$TRAVIS_OS_NAME" != osx || brew outdated netpbm || brew upgrade netpbm
  - test "$TRAVIS_OS_NAME" != osx || brew outdated proj || brew upgrade proj
  - test "$TRAVIS_OS_NAME" != osx || brew outdated wxmac || brew upgrade wxmac
  - test "$TRAVIS_OS_NAME" != osx || brew outdated libav || brew upgrade libav
script:
  - autoreconf -fiv
  - ./configure
  - make
  - make check
branches:
  only:
    - master
